### ISSUE TITLE
how about replace FPoint FRect to System.Numerics struct?

### ISSUE THREAD

**Issue by Gascognya** [edwardgushchin/SDL3-CS#16]
`FPoint(float x, float y)` -> `System.Numerics.Vector2(float x, float y)`
`FRect(float x, float y, float w, float h)` -> `System.Numerics.Vector4(float x, float y, float z, float w)`
They have similar definitions, And more friendly to .NET.

**Comment by edwardgushchin** [comment]
@Gascognya Hi! I'm not sure how good this idea is, because these structures are actively marshaled. Also, it will confuse many people. But in general, nothing prevents you from implementing a cast to these types inside FRect and FPoint.
