### ISSUE TITLE
Support for SDL_image, SDL_mixer and SDL_ttf

### ISSUE THREAD

**Issue by MasterGordon** [edwardgushchin/SDL3-CS#18]
Loving your bindings, awesome work!
Please add support for the other sdl libraries like SDL_image, SDL_mixer and SDL_ttf :D

https://wiki.libsdl.org/SDL3/Libraries

**Comment by edwardgushchin** [comment]
Thank you! I plan to start working on them right after the main library :)

**Comment by edwardgushchin** [comment]
@MasterGordon Hi! All done :)
