### ISSUE TITLE
native library as standalone package

### ISSUE THREAD

**Issue by Gascognya** [edwardgushchin/SDL3-CS#19]
NativeAOT allow linking **Static Library** or **Import Library**(.lib from .dll). 
So, maybe native library should be optional, allow user's SDL build. 
And the ImportResolver was a problem.

**Comment by edwardgushchin** [comment]
Do you think it would be a good idea to shift the responsibility for SDL3 libraries to the user? In that case, there would be no guarantee that the shell is fully compliant with the custom version of SDL3.

I've given a lot of thought to what would be best, and to be honest, I've been leaning towards the idea of doing away with the rigid binding to specific builds for a long time now.

**Comment by Gascognya** [comment]
Your concern is correct.

But I believe that users know what they are doing and are aware of the consequences.

Just like the "unsafe" in the safe language, this is a disclaimer.

May be the Main "SDL3-CS" package depend on "SDL3-CS.Bindings" package and "SDL3-CS.Native" package is a compromise solution?

Default, but allow cheat.

**Comment by edwardgushchin** [comment]
I agree. Besides, all these builds for multiple platforms are quite costly to maintain. I'll leave it to the user.

**Comment by Gascognya** [comment]
we should declare the binding sdl version, maybe synchronization between sdl3-cs and sdl3 versions? or sdl version + fix version.

And we can provide a simple standalone package include mainstream platforms (desktop x64), for **develop** and **examples running**. (maybe copy from the official release build? if they can release on time).

**Comment by edwardgushchin** [comment]
I was planning to do the Nuget release as a package at the same time as the SDL release, so that the versions would be the same (SDL-CS 3.2.1 -> SDL 3.2.1).

The standalone package is a good idea, you can do it together with the SDL release when they roll out the official builds.
